services:
  - type: web
    name: securestaff
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    branch: master
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
